### ISSUE TITLE
Including RSpec::Matchers in Page classes will mess up `elements` and `sections`

### ISSUE THREAD

**Issue by yijia-zhan** [natritmeyer/site_prism#102] opened 2015-02-03 01:37 UTC
I want to move some assertions  to inside the Page class, and for that I need to `include RSpec::Matchers`. However, doing so will turn `elements` and `sections` into `RSpec::Matchers::BuiltIn::All`. 

For example:

```ruby
class HomePage < SitePrism::Page
  sections :menu_items, MenuItemClass, "ul#menu li"

  def test_method
    binding.pry
  end
end
```
In the code above, if I'm at the `binding.pry`, `menu_items` will return an array of menu items as expected. 

However, if I included `RSpec::Matchers` as following:

```ruby
class HomePage < SitePrism::Page
  include RSpec::Matchers

  sections :menu_items, MenuItemClass, "ul#menu li"

  def test_method
    binding.pry
  end
end
```

And if I  try to call `menu_items` at the `binding.pry`, I will get an error at `lib/site_prism/element_container.rb:33`:
>NoMethodError: undefined method `collect' for #<RSpec::Matchers::BuiltIn::All:0x007fd462d29ae0>

So if included `RSpec::Matcher`, instead of returning an Array, `find_all(*find_args, *runtime_args)` in the `sections` method will return a `RSpec::Matchers::BuiltIn::All` which does respond_to `:collect`. 

```ruby
def sections(section_collection_name, *args, &block)
    section_class, find_args = extract_section_options args, &block
    build section_collection_name, *find_args do
      define_method section_collection_name do |*runtime_args|
        find_all(*find_args, *runtime_args).collect do |element|
          section_class.new self, element
        end
      end
    end
  end
```

**Comment by abotalov** [comment] 2015-02-03 06:25
Duplicate of https://github.com/natritmeyer/site_prism/issues/95

**Comment by abotalov** [comment] 2015-02-03 06:27
I believe to fix it `all` should be changed to `page.all`.

**Comment by yijia-zhan** [comment] 2015-02-03 19:36
Thanks for the help @abotalov! I tested it out and it did make the code work. Not sure if there are side-effects of this change though. I'll send a pull request.

**Closed** 2015-07-07 09:03 UTC
